name: deformnet
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pip
  - blas
  - blosc
  - brotli
  - brotli-bin
  - brotlipy
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - cfitsio
  - charls
  - charset-normalizer
  - click
  - cloudpickle
  - colorama
  - cryptography
  - cudatoolkit
  - cycler
  - cytoolz
  - dask-core
  - et_xmlfile
  - fonttools
  - freeglut
  - freetype
  - fsspec
  - giflib
  - icu
  - idna
  - imagecodecs
  - imageio
  - imutils
  - intel-openmp
  - jasper
  - joblib
  - jpeg
  - kiwisolver
  - lcms2
  - lerc
  - libaec
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libdeflate
  - liblapack
  - liblapacke
  - libopencv
  - libpng
  - libprotobuf
  - libtiff
  - libuv
  - libwebp
  - libwebp-base
  - libzopfli
  - locket
  - lz4-c
  - m2w64-gcc-libgfortran
  - m2w64-gcc-libs
  - m2w64-gcc-libs-core
  - m2w64-gmp
  - m2w64-libwinpthread-git
  - matplotlib-base
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - msys2-conda-epoch
  - munkres
  - networkx
  - numpy
  - numpy-base
  - opencv
  - openjpeg
  - openpyxl
  - openssl
  - packaging
  - pandas
  - partd
  - pillow
  - py-opencv
  - pycparser
  - pyopenssl
  - pyparsing
  - pysocks
  - python
  - python-dateutil
  - python_abi
  - pytorch
  - pytorch-model-summary
  - pytorch-mutex
  - pytz
  - pywavelets
  - pyyaml
  - qt
  - requests
  - scikit-image
  - scikit-learn
  - scipy
  - setuptools
  - six
  - snappy
  - sqlite
  - threadpoolctl
  - tifffile
  - toolz
  - torchvision
  - tqdm
  - typing_extensions
  - tzdata
  - unicodedata2
  - urllib3
  - vc
  - vs2015_runtime
  - wheel
  - win_inet_pton
  - wincertstore
  - xz
  - yaml
  - zfp
  - zlib
  - zstd
  - pip:
    - absl-py
    - astunparse
    - cachetools
    - flatbuffers
    - gast
    - google-auth
    - google-auth-oauthlib
    - google-pasta
    - grpcio
    - h5py
    - imgaug
    - importlib-metadata
    - keras
    - keras-preprocessing
    - libclang
    - lpips
    - markdown
    - markupsafe
    - matlabengineforpython
    - oauthlib
    - opencv-python
    - opt-einsum
    - pip
    - protobuf
    - pyasn1
    - pyasn1-modules
    - requests-oauthlib
    - rsa
    - shapely
    - tensorboard
    - tensorboard-data-server
    - tensorboard-plugin-wit
    - tensorflow-estimator
    - tensorflow-gpu
    - tensorflow-io-gcs-filesystem
    - termcolor
    - tk
    - torch-utils
    - torchsummary
    - werkzeug
    - wrapt
    - zipp
